import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {app} from '../test-support/helper.mjs';
test('equipment details stay in advanced settings',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(html.indexOf('id="equipment-options"')>html.indexOf('id="advanced-setup"'));});
test('gym setup cannot silently generate bodyweight plan without equipment confirmation',()=>{const a=app();a.run("setup.elements.namedItem=name=>({value:({safetySymptoms:'no',safetyReview:'no',name:'测试',goal:'增肌与体型塑造',place:'健身房',experience:'有规律训练经验',days:'3',minutes:'90',sleepTarget:'7'})[name]||''});generatePlan()");assert.ok(a.run("document.querySelector('#setup-feedback').textContent.includes('请选择实际可用')"));assert.notEqual(a.run('state.profile.place'),'健身房');});
test('gym chest plan uses available weights and bodyweight plan avoids duplicate difficulty versions',()=>{const a=app();a.run("state.profile={goal:'增肌与体型塑造',place:'健身房',experience:'有规律训练经验',minutes:'90',days:'3',split:'full',equipment:['杠铃','哑铃','训练凳','龙门架 / 绳索器械']};state.plannedWorkouts ||= {};state.plannedWorkouts['2026-10-20']={trainingPreferences:{muscleFocus:'chest',exerciseCount:'5'}}");assert.ok(a.run("prescription(new Date(2026,9,20)).ids.some(id=>recordingMode(id)==='weighted')"));assert.ok(a.run("prescription(new Date(2026,9,20)).ids.every(id=>!['push','pushup'].includes(id))"));a.run("state.profile.equipment=['无器械 / 徒手']");assert.ok(!a.run("(()=>{const ids=prescription(new Date(2026,9,20)).ids;return ids.includes('push')&&ids.includes('pushup')})()"));});

test('gym defaults contain common weights while home remains bodyweight',()=>{const a=app();assert.ok(a.run("defaultEquipment('健身房').includes('杠铃')"));assert.ok(!a.run("defaultEquipment('健身房').includes('无器械 / 徒手')"));assert.equal(a.run("defaultEquipment('家中').join(',')"),'无器械 / 徒手');a.run("state.profile.place='健身房';state.profile.equipment=['哑铃'];setup.elements.place.value='健身房';openSetup()");assert.ok(a.run("document.querySelector('#equipment-options').innerHTML.includes('value=\"哑铃\" checked')"));assert.ok(!a.run("document.querySelector('#equipment-options').innerHTML.includes('value=\"杠铃\" checked')"));});
