import test from 'node:test';import assert from 'node:assert/strict';import{behaviourAchievements,monthCells,trainingCSV,bestPerformance}from'../modules/insights.js';import{app}from'../test-support/helper.mjs';
test('achievements reward participation learning and planned recovery independently of weight',()=>{const history={'2026-10-01':{done:true,logs:{squat:[{reps:8,weight:0}]},learnedMoves:Array.from({length:10},(_,i)=>'move'+i)},'2026-10-02':{rest:true,recoveryFeedback:true}};const result=behaviourAchievements(history,{control:{},patterns:{}},d=>!!d.done,date=>date==='2026-10-02','2026-10-08');assert.ok(result.find(a=>a.id==='first').earned);assert.ok(result.find(a=>a.id==='explorer').earned);assert.ok(result.find(a=>a.id==='recovery').earned);assert.ok(result.find(a=>a.id==='stage-foundation').earned);assert.equal(behaviourAchievements(history,{},d=>false,()=>false,'2026-09-30').filter(a=>a.earned).length,0);});
test('calendar lays out Monday-first months including leap years',()=>{const cells=monthCells(2026,9);assert.equal(cells.filter(x=>!x).length,3);assert.equal(cells.filter(Boolean).length,31);assert.equal(monthCells(2024,1).filter(Boolean).length,29);});
test('CSV preserves dumbbell basis and prevents spreadsheet formula injection',()=>{const csv=trainingCSV({'2026-10-08':{logs:{db:[{weight:10,reps:8,weightUnit:'per-dumbbell',setup:'=1+1'}],run:[{minutes:12,effort:'轻松'}]}}},{db:{name:'哑铃,卧推'},run:{name:'跑步'}});assert.ok(csv.includes('单只哑铃'));assert.ok(csv.includes('"kg"'));assert.ok(csv.includes("'=1+1"));assert.ok(csv.includes('"12"'));assert.equal(csv.split('\r\n').length,3);});
test('best records keep variants and old mass semantics separate',()=>{const records=bestPerformance({'2026-10-08':{logs:{bench:[{weight:40,reps:8,weightUnit:'total'},{weight:45,reps:6,weightUnit:'total'},{weight:100,reps:5}],db:[{weight:20,reps:10,weightUnit:'per-dumbbell'}]}}},{},'2026-10-08');assert.equal(records.length,3);assert.equal(records.find(r=>r.basis==='total').weight,45);});
test('backup reminders require confirmation and personal records do not award XP',()=>{const a=app();a.run(`state.onboarded=true;activateFoundationRewards();today().personalRecord={waist:85,note:'精神不错'};state.backupRequestedAt=dateKey()`);assert.equal(a.run('points(today())'),0);assert.ok(a.run('backupReminderPanel()').includes('成功保存'));a.run('state.backupConfirmedAt=dateKey()');assert.equal(a.run('backupReminderPanel()'),'');assert.ok(a.run(`parseBackup(JSON.stringify({profile:{goal:'建立运动习惯',place:'家中',experience:'初学者',minutes:'15'},history:{[dateKey()]:today()}})).history[dateKey()].personalRecord`));});
test('new backup validation rejects injected photo URLs and malformed body measurements',()=>{const a=app();const base={profile:{goal:'建立运动习惯',place:'家中',experience:'初学者',minutes:'15'},history:{}};for(const patch of [{progressPhotos:[{date:'2026-10-08',data:'javascript:alert(1)'}]},{history:{'2026-10-08':{personalRecord:{waist:0,note:'test'}}}}])assert.throws(()=>a.run(`parseBackup(${JSON.stringify(JSON.stringify({...base,...patch}))})`));});

test('awarded achievements persist independently of weekly reset',()=>{const a=app();a.run(`today().rest=false;today().exerciseIds=['squat'];today().targets={squat:{sets:1,min:8,max:12}};today().logs={squat:[{weight:0,reps:8}]};achievementsPanel();`);assert.ok(a.run('state.achievementDates.first'));assert.ok(app(a.saved()).run('achievementsPanel()').includes('✦ 第一次出发'));});
