import test from 'node:test';import assert from 'node:assert/strict';
import {translateText,setLanguage,currentLanguage,uiText} from '../modules/localization.js';
import {englishMovements,movementPhrases} from '../modules/locales/en-movements.js';
import {app} from '../test-support/helper.mjs';
import {trainingCSV} from '../modules/insights.js';
test('every catalog movement and cue has an English translation with stable IDs',()=>{const catalog=app().run('catalog');assert.equal(Object.keys(catalog).length,138);for(const [id,m] of Object.entries(catalog)){assert(englishMovements[id]);assert.equal(translateText(m.name),englishMovements[id].name);assert.equal(englishMovements[id].cues.length,m.cues.length);for(const cue of m.cues){assert(movementPhrases[cue]);assert(!/[\u3400-\u9fff]/.test(translateText(cue)));}}});
test('dynamic safety, load and schedule labels keep their numbers and units',()=>{for(const text of ['第 2 步 / 共 6 步','首次记录：建议 4 组 × 8–12 次，保留约 3 次余力，先用轻重量试做 6–8 次，确认动作稳定，再小幅调整；热身试做不计工作组。器械空载和杠铃自身重量也计入实际负重。','单只哑铃重量 lb（使用 2 只）','训练日：练 1 天 / 休 2 天 · 从 2026-10-09 循环','胸痛、晕厥或异常严重气促需要及时医疗评估；症状严重或持续时联系当地急救服务。']){const translated=translateText(text);assert(!/[\u3400-\u9fff]/.test(translated),translated);assert.deepEqual(translated.match(/\d+(?:\.\d+)?/g),text.match(/\d+(?:\.\d+)?/g));}assert.match(translateText('单只哑铃重量 lb（使用 2 只）'),/lb/);});
test('CSV translation does not translate user authored setup or change canonical mass',()=>{const state={logs:{bench:[{weight:20,reps:8,weightUnit:'total',setup:'肩部疼痛，用户原文'}]}};const csv=trainingCSV({'2026-10-09':state},{bench:{name:'Bench Press · 卧推'}},()=> 'weighted',translateText);assert.match(csv,/'?肩部疼痛，用户原文/);assert.match(csv,/"Exercise ID"/);assert.match(csv,/"20","kg"/);assert.match(csv,/"Barbell bench press"/);});
test('language changes display without touching canonical records',()=>{const a=app();const before=a.run('JSON.stringify(state)');setLanguage('en');assert.equal(currentLanguage(),'en');assert.equal(uiText('暂停训练'),'Pause workout');setLanguage('zh');assert.equal(uiText('暂停训练'),'暂停训练');assert.equal(a.run('JSON.stringify(state)'),before);});
