import {test} from 'node:test';import assert from 'node:assert/strict';import {app} from '../test-support/helper.mjs';
test('goal × time × experience × equipment × schedule × split matrix',()=>{
const a=app();const result=a.run(`(()=>{
const goals=['建立运动习惯','减脂与体重管理','增肌与体型塑造','提升力量','提升心肺与耐力','灵活性与日常活动能力','保持健康与精力'];
const times=${JSON.stringify(process.env.STREAKFIT_BOUNDARIES?[20,29,44,61,91,119,150]:[10,15,25,30,45,60,90,120,180])};const experiences=['初学者','有一些经验 / 重新开始','有规律训练经验'];
const kits=[{place:'家中',equipment:[]},{place:'家中',equipment:['哑铃']},{place:'健身房',equipment:['哑铃','杠铃','训练凳','深蹲架 / 保护架','龙门架 / 绳索器械','腿举机','高位下拉机','跑步机','硬拉台（Deadlift platform）']},{place:'户外 / 公园',equipment:['弹力带']}];
const schedules=[{scheduleMode:'weekly',weekdays:[0,2,4],days:'3'},{scheduleMode:'weekly',weekdays:[0,1,2,3,4,5,6],days:'7'},...[[3,1],[4,1],[1,1],[1,2]].map(([t,r])=>({scheduleMode:'cycle',trainDays:String(t),restDays:String(r),days:'3'}))];
let count=0;const failures=[];
for(const goal of goals)for(const minutes of times)for(const experience of experiences)for(const kit of kits)for(const scheduleSettings of schedules)for(const split of ['auto','full','upperlower','ppl']){
state.profile={goal,minutes:String(minutes),experience,...kit,...scheduleSettings,split,scheduleStart:'2026-10-05',name:'测试'};state.history={};state.exerciseTargets={};state.exerciseReplacements={};
try{for(const offset of [0,1,2,7]){const plan=prescription(new Date(2026,9,5+offset));if(!plan.ids.length)throw Error('empty');if(new Set(plan.ids).size!==plan.ids.length)throw Error('duplicate');if(!plan.ids.every(id=>catalog[id]&&supports(id)))throw Error('equipment');if(plan.estimated>minutes)throw Error('time '+plan.estimated);for(const id of plan.ids){if(catalog[id].kind==='cardio'){if(!Number.isFinite(plan.durations?.[id])||plan.durations[id]<=0)throw Error('duration');}else{const t=exerciseTarget(id);if(t.min>t.max||t.sets<1)throw Error('target');}}}
page='workout';render();if(/NaN|undefined/.test(content.innerHTML))throw Error('render');if(goal==='提升心肺与耐力'||goal==='灵活性与日常活动能力'){if(content.innerHTML.includes('id="weight-'))throw Error('wrong control');}if(!Number.isFinite(points(today()))||points(today())!==0)throw Error('xp');
}catch(error){if(failures.length<30)failures.push({goal,minutes,experience,kit:kit.place,schedule:scheduleSettings,split,error:error.message});}count++;}
return {count,failures};})()`);
assert.equal(result.failures.length,0,JSON.stringify(result));console.log(`Validated ${result.count} configurations, four dates each, and workout renders`);
});
test('goals have distinct executable strategies with identical input conditions',()=>{const a=app();const signatures=a.run(`['建立运动习惯','减脂与体重管理','增肌与体型塑造','提升力量','提升心肺与耐力','灵活性与日常活动能力','保持健康与精力'].map(goal=>{state.profile={goal,minutes:'60',days:'3',place:'家中',equipment:['哑铃'],experience:'有规律训练经验'};const p=prescription();return JSON.stringify({ids:p.ids,target:goalTarget(),duration:p.durations});})`);assert.equal(new Set(signatures).size,7);});
test('all weekday selections and cycle counts remain correct through 60 dates',()=>{const a=app();const result=a.run(`(()=>{let checked=0;for(let mask=1;mask<128;mask++){const days=Array.from({length:7},(_,i)=>i).filter(i=>mask&(1<<i));state.profile={scheduleMode:'weekly',weekdays:days,scheduleStart:'2026-10-05'};let ordinal=0;for(let offset=0;offset<60;offset++){const date=new Date(2026,9,5+offset);if(trainingOrdinal(date)!==ordinal)throw Error('weekly ordinal');const train=days.includes((date.getDay()+6)%7);if(schedule(date)!==(train?'training':'recovery'))throw Error('weekly date');if(train)ordinal++;checked++;}}for(let t=1;t<=7;t++)for(let r=1;r<=7;r++){state.profile={scheduleMode:'cycle',trainDays:t,restDays:r,scheduleStart:'2026-10-28'};let ordinal=0;for(let offset=0;offset<60;offset++){const date=new Date(2026,9,28+offset);if(trainingOrdinal(date)!==ordinal)throw Error('cycle ordinal');const train=offset%(t+r)<t;if(schedule(date)!==(train?'training':'recovery'))throw Error('cycle date');if(train)ordinal++;checked++;}}return checked;})()`);assert.equal(result,10560);});
