import {test} from 'node:test';import assert from 'node:assert/strict';import {app} from '../test-support/helper.mjs';
const profile={goal:'提升力量',place:'健身房',equipment:['哑铃','杠铃','训练凳','深蹲架 / 保护架','龙门架 / 绳索器械','腿举机','高位下拉机'],experience:'有规律训练经验',minutes:'120',split:'upperlower',scheduleMode:'weekly',scheduleStart:'2026-10-05',weekdays:[0,1,3,4],days:'4'};
test('same upper-body pattern rotates heavy volume and light exposures',()=>{const a=app();a.run(`state.profile=${JSON.stringify(profile)}`);const plans=[5,8,12].map(day=>JSON.parse(a.run(`JSON.stringify(prescription(new Date(2026,9,${day})))`)));assert.deepEqual(plans.map(p=>p.cycle.session),['重训练','训练量','技术轻练']);assert.deepEqual(plans.map(p=>p.targets.bench.min),[4,6,6]);assert.deepEqual(plans.map(p=>p.targets.bench.sets),[4,4,3]);assert.deepEqual(plans.map(p=>p.entries.find(e=>e.id==='bench').rest),[180,150,90]);});
test('fourth calendar week deloads targets and custom values remain priority',()=>{const a=app();a.run(`state.profile=${JSON.stringify({...profile,goal:'增肌与体型塑造'})}`);const first=JSON.parse(a.run('JSON.stringify(prescription(new Date(2026,9,5)))'));const fourth=JSON.parse(a.run('JSON.stringify(prescription(new Date(2026,9,26)))'));assert.equal(fourth.cycle.deload,true);assert.equal(first.targets.bench.sets,4);assert.equal(fourth.targets.bench.sets,2);assert.equal(first.targets.bench.rir,3);assert.equal(fourth.targets.bench.rir,4);a.run('state.exerciseTargets={bench:{sets:5,min:5,max:8}}');assert.equal(a.run('prescription(new Date(2026,9,26)).targets.bench.sets'),5);});
test('beginner stays in technical adaptation rather than experienced heavy loading',()=>{const a=app();a.run(`state.profile=${JSON.stringify({...profile,experience:'初学者'})}`);assert.equal(a.run('prescription(new Date(2026,9,5)).cycle.session'),'技术适应');assert.equal(a.run('prescription(new Date(2026,9,5)).targets.dbpress.min'),6);});
test('cardio stays stable without completion evidence and deloads within budget',()=>{const a=app();a.run(`state.profile=${JSON.stringify({...profile,goal:'提升心肺与耐力',minutes:'40',experience:'初学者'})}`);const durations=[5,12,19,26].map(day=>a.run(`prescription(new Date(2026,9,${day})).durations.march`)); // gym without cardio device uses march
assert.deepEqual(durations,[12,12,12,7]);assert.ok(a.run('prescription(new Date(2026,9,19)).estimated<=40'));});
test('route displays all 28 days and a deload phase',()=>{const a=app();a.run(`state.profile=${JSON.stringify(profile)};page='path';render()`);assert.equal(a.run('(content.innerHTML.match(/data-open-day=/g)||[]).length'),28);assert.ok(a.run('content.innerHTML.includes("减量恢复")'));});
test('automatic cycle split uses actual average frequency for repeated exposure',()=>{const a=app();a.run(`state.profile=${JSON.stringify({...profile,split:'auto',scheduleMode:'cycle',trainDays:'1',restDays:'1'})}`);assert.equal(a.run('prescription(new Date(2026,9,5)).cycle.exposure'),0);assert.equal(a.run('prescription(new Date(2026,9,7)).cycle.exposure'),0);assert.equal(a.run('prescription(new Date(2026,9,9)).cycle.exposure'),1);});
test('all goals and time budgets remain valid through deload and a new block',()=>{const a=app();const count=a.run(`(()=>{let count=0;for(const goal of ['建立运动习惯','减脂与体重管理','增肌与体型塑造','提升力量','提升心肺与耐力','灵活性与日常活动能力','保持健康与精力'])for(const minutes of [10,15,30,60,90,120,180])for(const experience of ['初学者','有规律训练经验'])for(const day of [5,12,19,26,33]){state.profile={goal,minutes:String(minutes),experience,place:'健身房',equipment:['哑铃','杠铃','训练凳','深蹲架 / 保护架','龙门架 / 绳索器械','高位下拉机','腿举机'],days:'4',split:'upperlower',scheduleMode:'weekly',weekdays:[0,1,3,4],scheduleStart:'2026-10-05'};state.history={};state.exerciseTargets={};const plan=prescription(new Date(2026,9,day));if(!plan.ids.length||new Set(plan.ids).size!==plan.ids.length||plan.estimated>minutes)throw Error(JSON.stringify({goal,minutes,experience,day,plan}));count++;}return count;})()`);assert.equal(count,490);});
