import test from 'node:test';import assert from 'node:assert/strict';import {app} from '../test-support/helper.mjs';
const profile={goal:'提升力量',place:'健身房',experience:'有规律训练经验',minutes:'120',split:'full',scheduleMode:'cycle',scheduleStart:'2026-10-05',trainDays:'4',restDays:'1'};
function setup(extra={}){const a=app();a.run(`state.profile=${JSON.stringify({...profile,...extra})};state.profile.equipment=equipmentByPlace['健身房'];state.history={};state.plannedWorkouts={}`);return a;}
function plan(a,day=5){return JSON.parse(a.run(`JSON.stringify(prescription(new Date(2026,9,${day})))`));}
test('identical input selects distinct strength technique and hypertrophy muscle work',()=>{for(const split of ['full','upperlower','ppl'])for(const minutes of ['90','120']){const a=setup({split,minutes});const strength=plan(a);assert.ok(strength.ids.includes('pausebench'));assert.equal(strength.targets.pausebench.min,3);assert.equal(strength.targets.pausebench.max,5);assert.equal(strength.targets.pausebench.rir,3);assert.equal(strength.entries.find(e=>e.id==='bench').role,'main');assert.equal(strength.entries.find(e=>e.id==='pausebench').role,'technique');a.run("state.profile.goal='增肌与体型塑造'");const hypertrophy=plan(a);assert.ok(hypertrophy.ids.every(id=>!a.run(`catalog['${id}'].advanced`)));assert.notDeepEqual(strength.ids,hypertrophy.ids);assert.equal(hypertrophy.targets.bench.min,8);}});
test('each powerlift day has one main and at most one technical variation with functional assistance',()=>{const a=setup();for(const [focus,main,variant] of [['bench_day','bench','pausebench'],['squat_day','barsquat','pausesquat'],['deadlift_day','deadlift','pausedeadlift']]){a.run(`state.plannedWorkouts={'2026-10-10':{trainingPreferences:{muscleFocus:'${focus}',exerciseCount:'6'}}}`);const p=plan(a,10);assert.equal(p.ids[0],main);assert.ok(p.ids.includes(variant));assert.equal(p.entries.filter(e=>e.role==='main').length,1);assert.equal(p.entries.filter(e=>e.role==='technique').length,1);assert.ok(p.ids.includes('pallof'));assert.ok(p.entries.filter(e=>e.role==='assistance').every(e=>p.targets[e.id].sets<=3));assert.ok(p.estimated<=120);if(focus==='deadlift_day')assert.ok(!p.ids.includes('rdl'));}});
test('novice returning and limited kit do not get advanced paused barbell variations',()=>{const a=setup();for(const experience of ['初学者','有一些经验 / 重新开始'])for(const focus of ['balanced','bench_day','squat_day','deadlift_day']){a.run(`state.profile.experience=${JSON.stringify(experience)};state.plannedWorkouts={'2026-10-10':{trainingPreferences:{muscleFocus:'${focus}',exerciseCount:'6'}}}`);assert.ok(plan(a,10).ids.every(id=>!a.run(`catalog['${id}'].advanced`)));}a.run("state.profile.experience='有规律训练经验';state.profile.equipment=['哑铃'];state.plannedWorkouts={'2026-10-10':{trainingPreferences:{muscleFocus:'deadlift_day'}}}");assert.ok(plan(a,10).ids.every(id=>a.run(`supports('${id}')`)));assert.ok(!plan(a,10).ids.includes('pausedeadlift'));});
test('single-muscle strength request keeps that muscle with only one advanced variation',()=>{const a=setup();for(const [focus,muscle] of [['chest','胸部'],['quadriceps','股四头肌'],['hamstrings','腘绳肌']]){a.run(`state.plannedWorkouts={'2026-10-10':{trainingPreferences:{muscleFocus:'${focus}',exerciseCount:'8'}}}`);const p=plan(a,10);assert.ok(p.ids.every(id=>a.run(`catalog['${id}'].muscle===${JSON.stringify(muscle)}`)));assert.ok(p.ids.filter(id=>a.run(`catalog['${id}'].advanced`)).length<=1);assert.ok(p.ids.some(id=>a.run(`catalog['${id}'].advanced`)));}});
test('technical variation history uses its own load and explicit cues rather than main weight',()=>{const a=setup();a.run("state.history['2026-09-01']={logs:{bench:[{weight:100,reps:5}]}};state.plannedWorkouts={'2026-10-10':{trainingPreferences:{muscleFocus:'bench_day'}}};openWorkoutDay('2026-10-10')");assert.equal(a.run("suggestion('pausebench').weight"),0);assert.ok(a.run("suggestion('pausebench').text.includes('不从常规主项复制重量')"));assert.equal(a.run("selectedPrescription().targets.pallof.rir"),undefined);assert.equal(a.run("selectedPrescription().targets.pallof.perSide"),true);a.run("state.exerciseTargets={pausebench:{sets:2,min:4,max:6}};");assert.equal(plan(a,10).targets.pausebench.sets,2);assert.equal(plan(a,10).targets.pausebench.max,6);});
test('strength variations respect time deload equipment and non-repetition across dates',()=>{const a=setup();let count=0;for(const minutes of [10,30,60,90,120])for(const split of ['full','upperlower','ppl'])for(const focus of ['balanced','bench_day','squat_day','deadlift_day'])for(const day of [5,12,19,26]){a.run(`state.profile.minutes='${minutes}';state.profile.split='${split}';state.plannedWorkouts={'2026-10-${String(day).padStart(2,'0')}':{trainingPreferences:{muscleFocus:'${focus}',exerciseCount:'8'}}}`);const p=plan(a,day);assert.ok(p.estimated<=minutes);assert.equal(new Set(p.ids).size,p.ids.length);assert.ok(p.ids.every(id=>a.run(`supports('${id}')`)));assert.ok(p.entries.filter(e=>e.role==='technique').length<=1);count++;}assert.equal(count,240);});
