import test from 'node:test';import assert from 'node:assert/strict';import {app} from '../test-support/helper.mjs';
const base={goal:'增肌与体型塑造',experience:'初学者',place:'健身房',minutes:'30',split:'full',scheduleMode:'weekly',weekdays:[0,2,4],days:'3',scheduleStart:'2026-10-05'};
function init(a,profile={}){a.run(`state.profile=${JSON.stringify({...base,...profile})};state.profile.equipment ||= defaultEquipment(state.profile.place);state.history={};state.plannedWorkouts={};state.exerciseTargets={}`);}
function plan(a,day=5){return JSON.parse(a.run(`JSON.stringify(prescription(new Date(2026,9,${day})))`));}
test('short full-body plans cover push pull squat hinge across two weeks, even with actual logs',()=>{const a=app();let checked=0;for(const goal of ['增肌与体型塑造','减脂与体重管理','保持健康与精力'])for(const minutes of ['10','30','60'])for(const experience of ['初学者','有一些经验 / 重新开始','有规律训练经验'])for(const kit of [{place:'家中',equipment:['无器械 / 徒手']},{place:'家中',equipment:['哑铃']},{place:'健身房'}]){init(a,{goal,minutes,experience,...kit});const muscles=new Set();for(const day of [5,7,9,12,14,16]){const p=plan(a,day);assert.ok(p.estimated<=Number(minutes));for(const id of p.ids)muscles.add(a.run(`catalog['${id}'].muscle`));a.run(`state.history['2026-10-${String(day).padStart(2,'0')}']={exerciseIds:${JSON.stringify(p.ids)},targets:${JSON.stringify(p.targets)},logs:Object.fromEntries(${JSON.stringify(p.ids)}.filter(id=>catalog[id].kind!=='cardio').map(id=>[id,Array.from({length:${JSON.stringify(p.targets)}[id].sets},()=>({weight:0,reps:8}))]))}`);}for(const muscle of ['胸部','背部','股四头肌','腘绳肌'])assert.ok(muscles.has(muscle),`${goal}/${minutes}/${experience}/${kit.place}: missing ${muscle}`);checked++;}assert.equal(checked,81);});
test('short fallback applies experience options and keeps remembered replacements',()=>{const a=app();init(a,{equipment:['推胸机','哑铃','训练凳','杠铃','深蹲架 / 保护架'],minutes:'10'});assert.equal(plan(a).ids[0],'chestmachine');a.run("state.exerciseReplacements={chestmachine:'dbbench'}");assert.equal(plan(a).ids[0],'dbbench');});
test('health time increase preserves strength coverage instead of stealing its budget',()=>{const a=app();for(const place of ['家中','健身房'])for(const experience of ['初学者','有规律训练经验'])for(const day of [5,7,9]){init(a,{goal:'保持健康与精力',place,experience,minutes:'30'});const small=plan(a,day);a.run("state.profile.minutes='120'");const large=plan(a,day);assert.deepEqual(large.ids,small.ids);assert.equal(large.estimated,small.estimated);}});
test('returning lifter remains in adaptation until six completed sessions',()=>{const a=app();init(a,{goal:'提升力量',experience:'有一些经验 / 重新开始',minutes:'90'});let p=plan(a,12);assert.equal(p.cycle.session,'回归适应');assert.ok(Object.values(p.targets).every(t=>t.min>=6&&t.sets<=3));a.run("for(let i=1;i<=6;i++)state.history['2026-09-0'+i]={logs:{dbbench:Array.from({length:3},()=>({weight:10,reps:8}))}};");assert.notEqual(plan(a,12).cycle.session,'回归适应');});
test('weighted back specialty does not spend capacity on prone W and includes loaded pulling',()=>{const a=app();init(a,{experience:'有规律训练经验',minutes:'120'});a.run("state.profile.equipment=equipmentByPlace['健身房'];state.plannedWorkouts={'2026-10-20':{trainingPreferences:{muscleFocus:'back',exerciseCount:'8'}}}");const p=plan(a,20);assert.ok(!p.ids.includes('proneW'));assert.ok(p.ids.some(id=>['row','chestsupported','cablerow','machinerow'].includes(a.run(`catalog['${id}'].variantOf||'${id}'`))));if(p.backEmphasis==='lat')assert.ok(p.ids.some(id=>['pulldown','pullup','assistpull'].includes(a.run(`catalog['${id}'].variantOf||'${id}'`))));else assert.ok(p.ids.includes('proneY'));});
test('both A and B shoulder days honor recent chest load',()=>{const a=app();for(const previous of [false,true]){init(a,{experience:'有规律训练经验',minutes:'120'});a.run(`state.plannedWorkouts={'2026-10-20':{trainingPreferences:{muscleFocus:'shoulders'}}};state.history={'2026-10-19':{logs:{bench:Array.from({length:8},()=>({weight:40,reps:8}))}${previous?",trainingPreferences:{muscleFocus:'shoulders'}":''}}}`);const p=plan(a,20);assert.ok(!p.ids.some(id=>['shoulderpress','shouldermachine','barohp'].includes(id)));assert.ok(p.note.includes('本日不再追加肩推'));}});
test('capacity exhaustion presents recovery with honest cause',()=>{const a=app();init(a,{experience:'有规律训练经验',minutes:'120'});a.run("state.history={'2026-10-19':{logs:{bench:Array.from({length:20},()=>({weight:40,reps:8}))}}};state.plannedWorkouts={'2026-10-20':{trainingPreferences:{muscleFocus:'chest'}}};openWorkoutDay('2026-10-20')");const p=plan(a,20);assert.equal(p.ids.length,0);assert.equal(p.recoveryRecommended,true);assert.ok(p.selectionInfo.includes('容量')||p.selectionInfo.includes('直接组数'));assert.ok(a.run("content.innerHTML.includes('建议恢复')"));});
test('control actions use side-specific quality guidance and no RIR',()=>{const a=app();init(a,{experience:'有规律训练经验',minutes:'120',scheduleMode:'cycle',trainDays:'4',restDays:'1'});a.run("state.plannedWorkouts={'2026-10-20':{trainingPreferences:{muscleFocus:'core',exerciseCount:'2'}}};openWorkoutDay('2026-10-20')");assert.equal(a.run('selectedPrescription().targets.deadbug.rir'),undefined);assert.equal(a.run('selectedPrescription().targets.deadbug.quality'),true);assert.ok(a.run("suggestion('deadbug').text.includes('不追求力竭')"));assert.ok(a.run("content.innerHTML.includes('每侧次数')"));});
test('today summary uses actual targets, restoration status and mobility units',()=>{const a=app();init(a,{scheduleMode:'cycle',scheduleStart:a.run('dateKey()'),trainDays:'1',restDays:'1',minutes:'90'});a.run("page='today';render()");assert.ok(!a.run("content.innerHTML.includes('4 组 / 动作')"));assert.ok(a.run("content.innerHTML.includes('力量工作组')"));a.run("today().rest=true;render()");assert.ok(a.run("content.innerHTML.includes('选择并记录恢复')"));assert.ok(!a.run("content.innerHTML.includes('个力量工作组')"));a.run("today().rest=false;state.profile.goal='灵活性与日常活动能力';render()");assert.ok(a.run("content.innerHTML.includes('按组练习 · 每侧次数')"));});
test('cardio mode honors choice and progresses only from easy actual completion',()=>{const a=app();init(a,{goal:'提升心肺与耐力',minutes:'60'});a.run("state.plannedWorkouts={'2026-10-20':{trainingPreferences:{cardioMode:'bike'}}}");let p=plan(a,20);assert.equal(p.ids[1],'bike');const target=p.durations.bike;a.run(`state.history={'2026-10-19':{cardioTargets:{bike:${target}},logs:{bike:[{minutes:${target},effort:'轻松'}]}}}`);assert.ok(plan(a,20).durations.bike<=target+2);a.run("state.history['2026-10-19'].logs.bike[0].minutes=8;state.history['2026-10-19'].logs.bike[0].effort='较吃力'");assert.equal(plan(a,20).durations.bike,8);a.run("state.history={}");assert.equal(plan(a,20).durations.bike,target);});
test('daily preview explains realizable counts without saving preferences',()=>{const a=app();init(a,{experience:'有规律训练经验',minutes:'120',scheduleMode:'cycle',trainDays:'4',restDays:'1'});a.run("openWorkoutDay('2026-10-20')");const before=a.run('JSON.stringify(workoutDay())');const preview=a.run("previewDailyPreferences('chest','8')");assert.equal(preview.moves,3);assert.ok(preview.sets<=10);assert.equal(a.run('JSON.stringify(workoutDay())'),before);});
test('partial or distant old sessions do not end returning adaptation',()=>{const a=app();init(a,{goal:'提升力量',experience:'有一些经验 / 重新开始'});a.run("for(let i=1;i<=6;i++)state.history['2026-09-0'+i]={logs:{dbbench:[{weight:10,reps:8}]}};");assert.equal(plan(a,12).cycle.session,'回归适应');a.run("state.history={};for(let i=1;i<=6;i++)state.history['2025-09-0'+i]={logs:{dbbench:Array.from({length:4},()=>({weight:10,reps:8}))}};");assert.equal(plan(a,12).cycle.session,'回归适应');});
