const fs=require('node:fs');const assert=require('node:assert/strict');let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const errors=[],results=[];const goals=['建立运动习惯','减脂与体重管理','增肌与体型塑造','提升力量','提升心肺与耐力','灵活性与日常活动能力','保持健康与精力'];
for(const viewport of [{width:390,height:844},{width:1366,height:900}]){
const context=await browser.newContext({viewport});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
for(const goal of goals)for(const minutes of [15,120])for(const experience of ['初学者','有规律训练经验']){
await page.goto(process.env.STREAKFIT_URL||'http://127.0.0.1:3100/STREAKFIT.html');await page.evaluate(()=>{localStorage.clear()});await page.reload();await page.locator('[name=goal]').selectOption(goal);await page.locator('[name=minutes]').fill(String(minutes));await page.locator('[name=experience]').selectOption(experience);await page.locator('[name=scheduleStart]').fill('2026-10-05');await page.locator('#generate-plan').click();assert.equal(await page.locator('#dialog').evaluate(e=>e.open),false);await page.evaluate(()=>{page='workout';render()});const text=await page.locator('#content').innerText();assert.ok(!/NaN|undefined/.test(text));assert.ok(await page.locator('section.workout-card').count()>0);
const mobility=page.locator('[data-log-mobility]').first();const timed=page.locator('[data-log-cardio]').first();if(await mobility.count()){const id=await mobility.getAttribute('data-log-mobility');await mobility.click();assert.equal(await page.evaluate(id=>today().logs[id][0].mobilitySets,id),1);}else if(await timed.count()){const id=await timed.getAttribute('data-log-cardio');await page.locator('#cardio-minutes-'+id).fill('2');await timed.click();assert.equal(await page.evaluate(id=>today().logs[id][0].minutes,id),2);}else{const record=page.locator('[data-log]').first();const id=await record.getAttribute('data-log');const weighted=await page.locator('#weight-'+id).count();if(weighted){await page.locator('#weight-'+id).click();await page.keyboard.type('10');}await page.locator('#reps-'+id).click();await page.keyboard.type('8');await record.click();assert.equal(await page.evaluate(id=>today().logs[id][0].weight,id),weighted?10:0);}
const expected=await page.evaluate(()=>JSON.stringify(today().logs));await page.reload();assert.equal(await page.evaluate(()=>JSON.stringify(today().logs)),expected);await page.locator('#profile').click();await page.locator('[name=minutes]').fill('60');await page.locator('#generate-plan').click();assert.equal(await page.locator('#dialog').evaluate(e=>e.open),false);results.push({goal,minutes,experience,width:viewport.width});
}
await page.locator('#profile').click();await page.locator('[name=minutes]').fill('999');await page.locator('#generate-plan').click();assert.equal(await page.locator('#dialog').evaluate(e=>e.open),true);assert.ok((await page.locator('#setup-feedback').innerText()).length>0);await page.locator('[name=minutes]').fill('60');await page.locator('[name=sleepTarget]').fill('');await page.locator('#generate-plan').click();assert.equal(await page.locator('#dialog').evaluate(e=>e.open),true);await page.locator('[name=sleepTarget]').fill('7');await page.locator('[name=goal]').selectOption('增肌与体型塑造');await page.locator('#generate-plan').click();await page.evaluate(()=>{page='workout';render()});const targetButton=page.locator('[data-save-target]').first();const id=await targetButton.getAttribute('data-save-target');await page.locator('#target-sets-'+id).evaluate(e=>e.closest('details').open=true);await page.locator('#target-sets-'+id).fill('5');await page.locator('#target-min-'+id).fill('6');await page.locator('#target-max-'+id).fill('10');await targetButton.click();assert.equal(await page.evaluate(id=>exerciseTarget(id).sets,id),5);await page.locator('#target-sets-'+id).evaluate(e=>e.closest('details').open=true);await page.locator('#target-min-'+id).fill('20');await page.locator('#target-max-'+id).fill('5');await page.locator('[data-save-target]').first().click();assert.ok((await page.locator('#target-feedback-'+id).innerText()).includes('下限'));await context.close();}assert.equal(errors.length,0,errors.join('\n'));await browser.close();fs.writeFileSync('/workspace/workspace-streakfit/docs/browser-results.json',JSON.stringify({passed:results.length,errors,results},null,2));console.log('Browser workflows passed:',results.length);})();
